// examples/angular/src/app/tap-sides-to-seek/tap-sides-to-seek.component.ts
import { Component, ElementRef } from '@angular/core';
import { PlayerProp, usePlayerContext, PlayerDispatcher, createPlayerDispatcher } from '@vime/core';

@Component({
  selector: 'tap-sides-to-seek',
  templateUrl: './tap-sides-to-seek.component.html',
})
export class TapSidesToSeekComponent {
  dispatch!: PlayerDispatcher;

  currentTime = 0;

  duration = -1;

  /**
   * We need a reference to a DOM element so the Vime hooks work as they rely on dispatching 
   * custom DOM events.
   */
  constructor(private ref: ElementRef) {}

  ngAfterViewInit() {
    /**
     * Here we are creating a dispatcher to send updates to the player.
     */
    this.dispatch = createPlayerDispatcher(this.ref.nativeElement);
    
    /**
     * Here we are requesting to receive updates from the player, as the requested propties change 
     * it will be updated here.
     */
    usePlayerContext(
      this.ref.nativeElement,
      [PlayerProp.currentTime, PlayerProp.duration],
      (prop, value) => { this[prop] = value; }
    );
  }

  onSeekBackward() {
    if (this.currentTime < 5) return;
    // We are dispatching an update to the player to change the `currentTime` property.
    this.dispatch(PlayerProp.currentTime, this.currentTime - 5);
  }

  onSeekForward() {
    if (this.currentTime > (this.duration - 5)) return;
    this.dispatch(PlayerProp.currentTime, this.currentTime + 5);
  }
}

<div class="tapTarget backward" (click)="onSeekBackward()"></div>
<div class="spacer"></div>
<div class="tapTarget forward" (click)="onSeekForward()"></div>

<style>
  :host {
    display: flex;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 21;
    pointer-events: none;
  }

  :host > .spacer {
    flex: 1;
  }

  :host > .tapTarget {
    width: 7.5%;
    height: 100%;
    pointer-events: auto;
  }
</style>

// examples/vue/src/TapSidesToSeek.vue
<template>
  <div class="tapSidesToSeek">
    <div class="tapTarget backward" @click="onSeekBackward" />
    <div class="spacer" />
    <div class="tapTarget forward" @click="onSeekForward" />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { PlayerDispatcher, PlayerProp, usePlayerContext, createPlayerDispatcher } from '@vime/vue';

@Component()
export default class TapSidesToSeek extends Vue {
  dispatch!: PlayerDispatcher;

  currentTime = 0;

  duration = -1;

  mounted() {
    /**
     * Here we are creating a dispatcher to send updates to the player.
     */
    this.dispatch = createPlayerDispatcher(this.$el);

    /**
     * Here we are requesting to receive updates from the player, as the property changes it will be 
     * updated here.
     */
    usePlayerContext(
      this.$el,
      [PlayerProp.currentTime, PlayerProp.duration],
      (prop, value) => { this[prop] = value; },
    );
  }

  onSeekBackward() {
    if (this.currentTime < 5) return;
    // We are dispatching an update to the player to change the `currentTime` property.
    this.dispatch(PlayerProp.currentTime, this.currentTime - 5)
  };

  onSeekForward() {
    if (this.currentTime > (this.duration - 5)) return;
    this.dispatch(PlayerProp.currentTime, this.currentTime + 5)
  };
}
</script>

<style>
  .tapSidesToSeek {
    display: flex;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 21;
    pointer-events: none;
  }

  .tapSidesToSeek > .spacer {
    flex: 1;
  }

  .tapSidesToSeek > .tapTarget {
    width: 7.5%;
    height: 100%;
    pointer-events: auto;
  }
</style>
