// examples/vue-next/src/App.vue
<template>
  <div id="app">
    <div id="container">
      <VimePlayer
        playsinline
        ref="player"
        @vPlaybackReady="onPlaybackReady"
      >
        <VimeVideo poster="https://media.vimejs.com/poster.png">
          <source data-src="https://media.vimejs.com/720p.mp4" type="video/mp4">
        </VimeVideo>

        <VimeDefaultUi>
          <!-- Custom UI component. -->
          <TapSidesToSeek />
        </VimeDefaultUi>
      </VimePlayer>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { VimePlayer, VimeVideo, VimeDefaultUi } from '@vime/vue-next';

// Default theme.
import '@vime/core/themes/default.css';

// Optional light theme (extends default).
// import '@vime/core/themes/light.css';

// Custom UI Component.
import TapSidesToSeek from './TapSidesToSeek.vue';

export default defineComponent({
  name: 'App',
  components: {
    VimePlayer,
    VimeVideo,
    VimeDefaultUi,
    TapSidesToSeek,
  },
  setup() {
    // Obtain a ref if you need to call any methods.
    const player = ref<HTMLVimePlayerElement | null>(null);
    return { player };
  },
  methods: {
    onPlaybackReady() {
      // ...
    }
  },
});
</script>

<style>
#app {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

#container {
  width: 100%;
  max-width: 960px;
}
</style>

// examples/angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { VimePlayer } from '@vime/angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  // Obtain a ref if you need to call any methods.
  @ViewChild('player') player!: VimePlayer;

  onPlaybackReady() {
    // ...
  }
}

<div id="container">
  <vm-player #player playsinline (vPlaybackReady)="onPlaybackReady()">
    <vm-video cross-origin="true" poster="https://media.vimejs.com/poster.png">
      <source data-src="https://media.vimejs.com/720p.mp4" type="video/mp4" />
      <track
        default
        kind="subtitles"
        src="https://media.vimejs.com/subs/english.vtt"
        srclang="en"
        label="English"
      />
      <track
        kind="subtitles"
        src="https://media.vimejs.com/subs/spanish.vtt"
        srclang="es"
        label="Spanish"
      />
    </vm-video>

    <vm-default-ui>
      <!-- Custom UI component. -->
      <tap-sides-to-seek></tap-sides-to-seek>
    </vm-default-ui>
  </vm-player>
</div>

<style>
  :host {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  #container {
    width: 100%;
    max-width: 960px;
  }
</style>
