// packages/vime-standard/src/providers/Dailymotion.svelte
<LitePlayer 
  {src}
  {params}
  providers={[DailymotionProvider]}
  hasWrapper={false}
  on:error
  on:titlechange={onTitleChange}
  on:rebuild={onRebuildStart}
  on:litePlayerurlchange={onEmbedURLChange}
  on:data={onData}
  bind:this={litePlayer}
/>

<script context="module">
  import { can_play } from '@vime-js/core/dailymotion';

  const DM = {};

  // @see https://developer.dailymotion.com/player/#player-api-events
  DM.Event = {
    API_READY: 'apiready',
    VIDEO_CHANGE: 'videochange',
    VOLUME_CHANGE: 'volumechange',
    PLAYBACK_READY: 'playback_ready',
    SEEKING: 'seeking',
    SEEKED: 'seeked',
    WAITING: 'waiting',
    PROGRESS: 'progress',
    QUALITY_CHANGE: 'qualitychange',
    QUALITIES_AVAILABLE: 'qualitiesavailable',
    FULLSCREEN_CHANGE: 'fullscreenchange',
    DURATION_CHANGE: 'durationchange',
    PLAYING: 'playing',
    PLAY: 'play',
    PAUSE: 'pause',
    START: 'start',
    AD_START: 'ad_start',
    AD_PLAY: 'ad_play',
    AD_END: 'ad_end',
    TIME_UPDATE: 'timeupdate',
    VIDEO_START: 'video_start',
    VIDEO_END: 'video_end',
    ERROR: 'error',
  };

  // @see https://developer.dailymotion.com/player/#player-api-methods
  DM.Command = {
    PLAY: 'play',
    PAUSE: 'pause',
    SEEK: 'seek',
    DURATION: 'duration',
    VOLUME: 'volume',
    CONTROLS: 'controls',
    MUTED: 'muted',
    QUALITY: 'quality',
    FULLSCREEN: 'fullscreen',
  };

  export const canPlay = can_play;
</script>

<script>
  import { onMount, createEventDispatcher } from 'svelte';
  import { is_number, is_boolean } from '@vime-js/utils';
  import { Player as LitePlayer, DailymotionProvider } from '@vime-js/lite';
  import { fetch_poster, fetch_video_duration } from '@vime-js/core/dailymotion';
  import MediaType from '../MediaType';
  import PlayerState from '../PlayerState';

  let srcId;
  let litePlayer;
  let info = {};

  // DM commands don't go through until ads have finished, so we store them and then replay them
  // once the video starts.
  let startTime = null;
  let startVolume = null;
  let startMuted = null;
  let started = false;
  let isAdsPlaying = false;

  const params = {};
  const dispatch = createEventDispatcher();
  const send = (command, args) => litePlayer && litePlayer.sendCommand(command, args);

  export let src = null;

  export const getLitePlayer = () => litePlayer;
  export const getEl = () => (litePlayer ? litePlayer.getEmbed().getIframe() : null);

  export const setPlaysinline = () => { /** noop */ };
  export const setVideoQuality = (newQuality) => { send(DM.Command.QUALITY, [newQuality]); };
  export const setControls = (isEnabled) => { send(DM.Command.CONTROLS, [isEnabled]); };
  export const setFullscreen = (isActive) => { send(DM.Command.FULLSCREEN, [isActive]); };

  export const setPaused = (isPaused) => {
    isPaused ? send(DM.Command.PAUSE) : send(DM.Command.PLAY);
  };

  export const setMuted = (isMuted) => {
    if (!started) startMuted = isMuted;
    send(DM.Command.MUTED, [isMuted]);
  };

  export const setVolume = (newVolume) => {
    if (!started) startVolume = newVolume;
    send(DM.Command.VOLUME, [newVolume / 100]);
  };

  export const setCurrentTime = (newTime) => {
    if (!started) startTime = newTime;
    send(DM.Command.SEEK, [newTime]);
  };
  
  export const setView = (enabled) => {
    params['ui-logo'] = enabled;
    params['ui-start-screen-info'] = enabled;
  };

  export const supportsPiP = () => false;
  export const supportsFullscreen = () => true;

  onMount(() => { info.origin = litePlayer.getOrigin(); });
  onMount(() => { info.mediaType = MediaType.VIDEO; });
  
  const onRebuildStart = () => { info.rebuild = true; };
  const onTitleChange = (e) => { info.title = e.detail; };
  
  const onEmbedURLChange = (e) => {
    srcId = litePlayer.getSrcId();
    info.currentSrc = e.detail;
    info.srcId = srcId;
  };

  const onData = (e) => {
    const data = e.detail;
    const event = data && data.event;
    if (!event) return;
    switch (event) {
      case DM.Event.PLAYBACK_READY:
        startTime = null;
        startVolume = null;
        startMuted = null;
        started = false;
        isAdsPlaying = false;
        info.state = PlayerState.CUED;
        break;
      case DM.Event.START:
        info.state = PlayerState.BUFFERING;
        break;
      case DM.Event.VIDEO_START:
        if (started) return;
        if (is_number(startTime) && startTime > 0) {
          setCurrentTime(startTime);
          info.seeking = true;
        }
        if (is_boolean(startMuted)) setMuted(startMuted);
        if (is_number(startVolume)) setVolume(startVolume);
        started = true;
        break;
      case DM.Event.TIME_UPDATE:
        info.currentTime = parseFloat(data.time);
        break;
      case DM.Event.VOLUME_CHANGE:
        info.muted = (data.muted === 'true');
        info.volume = parseFloat(data.volume) * 100;
        break;
      case DM.Event.SEEKING:
        info.currentTime = parseFloat(data.time);
        info.seeking = true;
        break;
      case DM.Event.SEEKED:
        info.currentTime = parseFloat(data.time);
        info.seeked = true;
        break;
      case DM.Event.WAITING:
        info.state = PlayerState.BUFFERING;
        break;
      case DM.Event.PROGRESS:
        info.buffered = parseFloat(data.time);
        break;
      case DM.Event.QUALITIES_AVAILABLE:
        info.videoQualities = data.qualities.map((quality) => parseInt(quality, 10));
        break;
      case DM.Event.QUALITY_CHANGE:
        info.videoQuality = parseInt(data.quality, 10);
        break;
      case DM.Event.AD_START:
        isAdsPlaying = true;
        break;
      case DM.Event.AD_END:
        isAdsPlaying = false;
        break;
      case DM.Event.AD_PLAY:
        send(DM.Command.PLAY);
        break;
      case DM.Event.PLAY:
        info.play = true;
        break;
      case DM.Event.PLAYING:
        info.state = PlayerState.PLAYING;
        break;
      case DM.Event.PAUSE:
        info.state = PlayerState.PAUSED;
        break;
      case DM.Event.DURATION_CHANGE:
        if (!isAdsPlaying) info.duration = parseFloat(data.duration);
        break;
      case DM.Event.VIDEO_END:
        info.state = PlayerState.ENDED;
        break;
      case DM.Event.FULLSCREEN_CHANGE:
        info.fullscreen = !!data.fullscreen;
        break;
      case DM.Event.ERROR:
        dispatch('error', data);
        break;
      default:
        break;
    }
  };

  const fetchPoster = () => fetch_poster(src)
    .then((poster) => { info.poster = poster; })
    .catch((e) => dispatch('error', e));

  const fetchVideoDuration = () => fetch_video_duration(src)
    .then((duration) => { info.duration = duration; })
    .catch((e) => dispatch('error', e));

  $: fetchPoster(src);
  $: fetchVideoDuration(src);

  $: {
    dispatch('update', info);
    info = {};
  }
</script>

// packages/core/src/components/providers/dailymotion/dailymotion.tsx
import {
  h, Prop, Method, Component, Event, EventEmitter, State, Watch,
} from '@stencil/core';
import { MediaProvider, openProviderWormhole } from '../MediaProvider';
import { createPlayerStateDispatcher, PlayerStateDispatcher } from '../../core/player/PlayerState';
import { PlayerProp } from '../../core/player/PlayerProp';
import { decodeQueryString } from '../../../utils/network';
import { isString } from '../../../utils/unit';
import { ViewType } from '../../core/player/ViewType';
import { DailymotionParams } from './DailymotionParams';
import { DailymotionCommand, DailymotionCommandArg } from './DailymotionCommand';
import { DailymotionMessage } from './DailymotionMessage';
import { DeferredPromise, deferredPromise } from '../../../utils/promise';
import { DailymotionEvent } from './DailymotionEvent';
import { MediaType } from '../../core/player/MediaType';

@Component({
  tag: 'vime-dailymotion',
})
export class Dailymotion implements MediaProvider<HTMLVimeEmbedElement> {
  private embed!: HTMLVimeEmbedElement;

  private dispatch!: PlayerStateDispatcher;

  private initialMuted!: boolean;

  private defaultInternalState: any = {};

  private pendingVideoInfoFetch?: Promise<void>;

  private pendingMediaTitleFetch?: DeferredPromise<void>;

  private internalState = {
    currentTime: 0,
    volume: 0,
    muted: false,
    isAdsPlaying: false,
    playbackReady: false,
  };

  @State() embedSrc = '';

  @State() mediaTitle = '';

  /**
   * The Dailymotion resource ID of the video to load.
   */
  @Prop() videoId!: string;

  @Watch('videoId')
  onVideoIdChange() {
    this.embedSrc = `${this.getOrigin()}/embed/video/${this.videoId}?api=1`;
    this.internalState = { ...this.defaultInternalState };
    this.pendingVideoInfoFetch = this.fetchVideoInfo();
    this.pendingMediaTitleFetch = deferredPromise();
  }

  /**
   * Whether to automatically play the next video in the queue.
   */
  @Prop() shouldAutoplayQueue = false;

  /**
   * Whether to show the 'Up Next' queue.
   */
  @Prop() showUpNextQueue = false;

  /**
   * Whether to show buttons for sharing the video.
   */
  @Prop() showShareButtons = false;

  /**
   * Change the default highlight color used in the controls (hex value without the leading #).
   * Color set in the Partner HQ will override this prop.
   */
  @Prop() color?: string;

  /**
   * Forwards your syndication key to the player.
   */
  @Prop() syndication?: string;

  /**
   * Whether to display the Dailymotion logo.
   */
  @Prop() showDailymotionLogo = false;

  /**
   * Whether to show video information (title and owner) on the start screen.
   */
  @Prop() showVideoInfo = true;

  /**
   * @internal
   */
  @Prop() language = 'en';

  /**
   * @internal
   */
  @Prop() autoplay = false;

  /**
   * @internal
   */
  @Prop() controls = false;

  @Watch('controls')
  onControlsChange() {
    if (this.internalState.playbackReady) {
      this.remoteControl(DailymotionCommand.Controls, this.controls);
    }
  }

  /**
   * @internal
   */
  @Prop() debug = false;

  /**
   * @internal
   */
  @Prop() loop = false;

  /**
   * @internal
   */
  @Prop() muted = false;

  /**
   * @internal
   */
  @Prop() playsinline = false;

  /**
   * @internal
   */
  @Event() vLoadStart!: EventEmitter<void>;

  componentWillLoad() {
    this.dispatch = createPlayerStateDispatcher(this);
    this.dispatch(PlayerProp.ViewType, ViewType.Video);
    this.onVideoIdChange();
    this.initialMuted = this.muted;
    this.internalState.muted = this.muted;
    this.defaultInternalState = { ...this.internalState };
  }

  disconnectedCallback() {
    this.pendingVideoInfoFetch = undefined;
    this.pendingMediaTitleFetch = undefined;
  }

  private getOrigin() {
    return 'https://www.dailymotion.com';
  }

  private getPreconnections() {
    return [
      this.getOrigin(),
      'https://static1.dmcdn.net',
    ];
  }

  private remoteControl<T extends DailymotionCommand>(command: T, arg?: DailymotionCommandArg[T]) {
    return this.embed.postMessage({
      command,
      parameters: arg ? [arg] : [],
    });
  }

  private buildParams(): DailymotionParams {
    return {
      autoplay: this.autoplay,
      mute: this.initialMuted,
      'queue-autoplay-next': this.shouldAutoplayQueue,
      'queue-enable': this.showUpNextQueue,
      'sharing-enable': this.showShareButtons,
      syndication: this.syndication,
      'ui-highlight': this.color,
      'ui-logo': this.showDailymotionLogo,
      'ui-start-screen-info': this.showVideoInfo,
    };
  }

  private fetchVideoInfo() {
    const apiEndpoint = 'https://api.dailymotion.com';
    return window
      .fetch(`${apiEndpoint}/video/${this.videoId}?fields=duration,thumbnail_1080_url`)
      .then((response) => response.json())
      .then((data) => {
        this.dispatch(PlayerProp.CurrentPoster, data.thumbnail_1080_url);
        this.dispatch(PlayerProp.Duration, parseFloat(data.duration));
      });
  }

  private onEmbedSrcChange() {
    this.vLoadStart.emit();
  }

  private onEmbedMessage(event: CustomEvent<DailymotionMessage>) {
    const msg = event.detail;
    switch (msg.event) {
      case DailymotionEvent.PlaybackReady:
        this.onControlsChange();
        this.dispatch(PlayerProp.CurrentSrc, this.embedSrc);
        this.dispatch(PlayerProp.MediaType, MediaType.Video);
        Promise.all([
          this.pendingVideoInfoFetch,
          this.pendingMediaTitleFetch?.promise,
        ]).then(() => {
          this.dispatch(PlayerProp.PlaybackReady, true);
        });
        break;
      case DailymotionEvent.VideoChange:
        this.dispatch(PlayerProp.MediaTitle, msg.title!);
        this.pendingMediaTitleFetch?.resolve();
        break;
      case DailymotionEvent.Start:
        this.dispatch(PlayerProp.Paused, false);
        this.dispatch(PlayerProp.PlaybackStarted, true);
        this.dispatch(PlayerProp.Buffering, true);
        break;
      case DailymotionEvent.VideoStart:
        // Commands don't go through until ads have finished, so we store them and then replay them
        // once the video starts.
        this.remoteControl(DailymotionCommand.Muted, this.internalState.muted);
        this.remoteControl(DailymotionCommand.Volume, this.internalState.volume);
        if (this.internalState.currentTime > 0) {
          this.remoteControl(DailymotionCommand.Seek, this.internalState.currentTime);
        }
        break;
      case DailymotionEvent.Play:
        this.dispatch(PlayerProp.Paused, false);
        break;
      case DailymotionEvent.Pause:
        this.dispatch(PlayerProp.Paused, true);
        this.dispatch(PlayerProp.Playing, false);
        this.dispatch(PlayerProp.Buffering, false);
        break;
      case DailymotionEvent.Playing:
        this.dispatch(PlayerProp.Playing, true);
        this.dispatch(PlayerProp.Buffering, false);
        break;
      case DailymotionEvent.VideoEnd:
        if (this.loop) {
          setTimeout(() => { this.remoteControl(DailymotionCommand.Play); }, 300);
        } else {
          this.dispatch(PlayerProp.PlaybackEnded, true);
        }
        break;
      case DailymotionEvent.TimeUpdate:
        this.dispatch(PlayerProp.CurrentTime, parseFloat(msg.time!));
        break;
      case DailymotionEvent.VolumeChange:
        this.dispatch(PlayerProp.Muted, msg.muted === 'true');
        this.dispatch(PlayerProp.Volume, Math.floor(parseFloat(msg.volume!) * 100));
        break;
      case DailymotionEvent.Seeking:
        this.dispatch(PlayerProp.CurrentTime, parseFloat(msg.time!));
        this.dispatch(PlayerProp.Seeking, true);
        break;
      case DailymotionEvent.Seeked:
        this.dispatch(PlayerProp.CurrentTime, parseFloat(msg.time!));
        this.dispatch(PlayerProp.Seeking, false);
        break;
      case DailymotionEvent.Waiting:
        this.dispatch(PlayerProp.Buffering, true);
        break;
      case DailymotionEvent.Progress:
        this.dispatch(PlayerProp.Buffered, parseFloat(msg.time!));
        break;
      case DailymotionEvent.DurationChange:
        this.dispatch(PlayerProp.Duration, parseFloat(msg.duration!));
        break;
      case DailymotionEvent.QualitiesAvailable:
        this.dispatch(PlayerProp.PlaybackQualities, msg.qualities!.map((q: string) => `${q}p`));
        break;
      case DailymotionEvent.QualityChange:
        this.dispatch(PlayerProp.PlaybackQuality, `${msg.quality}p`);
        break;
      case DailymotionEvent.FullscreenChange:
        this.dispatch(PlayerProp.IsFullscreenActive, msg.fullscreen === 'true');
        break;
      case DailymotionEvent.Error:
        this.dispatch(PlayerProp.Errors, [new Error(msg.error!)]);
        break;
    }
  }

  /**
   * @internal
   */
  @Method()
  async getAdapter() {
    const canPlayRegex = /(?:dai\.ly|dailymotion|dailymotion\.com)\/(?:video\/|embed\/|)(?:video\/|)((?:\w)+)/;

    return {
      getInternalPlayer: async () => this.embed,
      play: async () => { this.remoteControl(DailymotionCommand.Play); },
      pause: async () => { this.remoteControl(DailymotionCommand.Pause); },
      canPlay: async (type: any) => isString(type) && canPlayRegex.test(type),
      setCurrentTime: async (time: number) => {
        this.internalState.currentTime = time;
        this.remoteControl(DailymotionCommand.Seek, time);
      },
      setMuted: async (muted: boolean) => {
        this.internalState.muted = muted;
        this.remoteControl(DailymotionCommand.Muted, muted);
      },
      setVolume: async (volume: number) => {
        this.internalState.volume = (volume / 100);
        this.dispatch(PlayerProp.Volume, volume);
        this.remoteControl(DailymotionCommand.Volume, (volume / 100));
      },
      canSetPlaybackQuality: async () => true,
      setPlaybackQuality: async (quality: string) => {
        this.remoteControl(DailymotionCommand.Quality, quality.slice(0, -1));
      },
      canSetFullscreen: async () => true,
      enterFullscreen: async () => { this.remoteControl(DailymotionCommand.Fullscreen, true); },
      exitFullscreen: async () => { this.remoteControl(DailymotionCommand.Fullscreen, false); },
    };
  }

  render() {
    return (
      <vime-embed
        embedSrc={this.embedSrc}
        mediaTitle={this.mediaTitle}
        origin={this.getOrigin()}
        params={this.buildParams()}
        decoder={decodeQueryString}
        preconnections={this.getPreconnections()}
        onVEmbedMessage={this.onEmbedMessage.bind(this)}
        onVEmbedSrcChange={this.onEmbedSrcChange.bind(this)}
        ref={(el: any) => { this.embed = el; }}
      />
    );
  }
}

openProviderWormhole(Dailymotion);
